version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: shopapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shopapi-network

volumes:
  pgdata:


networks:
  shopapi-network:
